export interface QuestionPaperConfig {
  totalMarks: number;
  totalQuestions: number;
  difficulty: string;
  parts: Array<{
    name: string;
    marks: number;
    questions: number;
    marksPerQuestion: number;
    choicesEnabled: boolean;
  }>;
}

export interface QuestionPaper {
  id: number;
  subjectName: string;
  generatedAt: Date;
  generatedBy: string;
  config: QuestionPaperConfig;
  questions: Array<{
    partName: string;
    question: string;
    marks: number;
  }>;
  content: string;
}

export function generatePaperContent(data: {
  subject: string;
  totalMarks: number;
  totalQuestions: number;
  difficulty: string;
  parts: string;
  content: string;
  questions?: string;
}): string {
  return `${data.subject} Question Paper
Time: 3 Hours
Total Marks: ${data.totalMarks}
Date: ${new Date().toLocaleDateString()}

Instructions:
1. Attempt all questions as per the instructions given for each part
2. Write your answers clearly and legibly
3. Start each answer on a new page
4. All questions carry marks as indicated

${data.questions || `
Paper Structure:
${data.parts}

Content Areas:
${data.content}
`}

Generated by Quizzy AI Paper Forge`;
}

export function downloadPaper(paper: QuestionPaper) {
  const blob = new Blob([paper.content], { type: 'text/plain;charset=utf-8' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${paper.subjectName.replace(/\s+/g, '_')}_Question_Paper.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
} 