// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://tctwiubpfaeskbuqpjfw.supabase.co';
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdHdpdWJwZmFlc2tidXFwamZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzU2ODQsImV4cCI6MjA2NzkxMTY4NH0.4NBtScrpz9V9RpNb9BVwyfk-ZkQEPV7OEDOjHGd9e-Y';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseKey);

// Faster network status check
export async function checkNetworkStatus(): Promise<boolean> {
  try {
    // Use a faster timeout for better responsiveness
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 2000); // Reduced from 3 to 2 seconds

    const response = await fetch('https://www.google.com/favicon.ico', {
      method: 'HEAD',
      mode: 'no-cors',
      signal: controller.signal,
    });

    clearTimeout(timeoutId);
    return true;
  } catch (error) {
    // Don't log AbortError as it's expected behavior
    if (error.name !== 'AbortError') {
      console.log('Network check failed:', error);
    }
    return false;
  }
}

// Enhanced error handling with faster response
export function handleNetworkError(error: any): string {
  console.error('Network error:', error);

  if (error.name === 'AbortError' || error.message?.includes('timeout')) {
    return 'Request timed out. Please check your internet connection and try again.';
  }

  if (error.message?.includes('Failed to fetch') || error.message?.includes('NetworkError')) {
    return 'Network error. Please check your internet connection and try again.';
  }

  if (error.message?.includes('Invalid login credentials')) {
    return 'Invalid email or password. Please check your credentials and try again.<br><br><strong>Need an account?</strong> <a href="/auth" style="color: #3b82f6; text-decoration: underline;">Sign up here</a>';
  }

  if (error.message?.includes('User not found')) {
    return 'No account found with this email address. Please check your email or create a new account.';
  }

  if (error.message?.includes('Too many requests')) {
    return 'Too many login attempts. Please wait a few minutes before trying again.';
  }

  if (error.message?.includes('Email not confirmed')) {
    return 'Please check your email and click the confirmation link to activate your account.';
  }

  if (error.message?.includes('Invalid email')) {
    return 'Please enter a valid email address.';
  }

  if (error.message?.includes('Password should be at least')) {
    return 'Password must be at least 6 characters long.';
  }

  return 'An unexpected error occurred. Please try again.';
}

export function getResetPasswordUrl(): string {
  return `${window.location.origin}/reset-password`;
}

// Function to validate and fix redirect URLs
export const validateRedirectUrl = (url: string): string => {
  try {
    const urlObj = new URL(url);
    
    // If it's localhost but wrong port, fix it
    if (urlObj.hostname === 'localhost' && urlObj.port !== '8080') {
      urlObj.port = '8080';
      return urlObj.toString();
    }
    
    return url;
  } catch (error) {
    console.error('Invalid URL:', url);
    return 'http://localhost:8080/reset-password';
  }
};